# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'corona-extract-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for corona-extract-ios

end
