# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'corona-extract-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for corona-extract-ios
	
	pod 'Alamofire', '~> 4.9.0'
	pod 'JGProgressHUD', '~> 2.1'
	pod 'LBTATools', '~> 1.0.12'
	pod 'R.swift'
	pod 'SDWebImage', '~> 5.2.3'
	pod 'SwiftLint'

end
